---

version: "3.7"

services:
  prom:
    image: prom/prometheus:v2.12.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  dashboard:
    image: grafana/grafana:6.3.3
    ports:
      - 3000:3000
