global:
  scrape_interval: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090
  # コンテナの情報を取得するためのcAdvisor
  # imageとコンテナ名の2つのLabelでうまく取得できない場合があるらしい
  # だからdropする
  - job_name: cadvisor
    static_configs:
      - targets:
        - 192.168.33.11:8080
    metric_relabel_configs:
      - regex: 'container_label_.*'
        action: labeldrop
